server {
    # 1. Настройки портов и домена

    server_name taskgym.ru www.taskgym.ru 93.125.18.142;

    # Логи (помогут при отладке бэкенда и фронтенда)
    access_log /var/log/nginx/taskgym.access.log;
    error_log /var/log/nginx/taskgym.error.log;

    # Включаем gzip-сжатие статики для быстрой загрузки
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss>

    # 2. Раздача загруженных картинок из бэкенда FastAPI напрямую
    location ^~ /uploads/ {
        # Точный путь к папке uploads вашего FastAPI приложения
        alias /var/www/learning_platform/backend/uploads/;

        # Кэшируем загруженные пользователями картинки на 7 дней
        expires 7d;
        add_header Cache-Control "public, no-transform";

        # Если файл физически отсутствует на диске, отдаем 404
        try_files $uri =404;
        # try_files $request_filename =404;
    }

    # 3. Кэширование картинок самого ФРОНТЕНДА (иконки, логотипы из сборки dist)
    location ~* \.(jpg|jpeg|png|gif|ico|webp|svg)$ {
        root /var/www/learning_platform/frontend/dist;
        expires 7d; # Кэшируем картинки в браузере на 7 дней для скорости
        add_header Cache-Control "public, no-transform";
    }

    # 4. Проксирование на бэкенд API (FastAPI)
    location /api/ {
           proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Для работы с вебсокетами / длинными запросами
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    # 5. Раздача фронтенда (Статика React + Vite)
    location / {
        root /var/www/learning_platform/frontend/dist;
        index index.html;
        try_files $uri $uri/ /index.html; # Важно для корректной работы путей React Router
    }

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/taskgym.ru/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/taskgym.ru/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}
server {
    if ($host = www.taskgym.ru) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = taskgym.ru) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80 default_server;
    listen [::]:80 default_server;

    server_name taskgym.ru www.taskgym.ru 93.125.18.142;
    return 404; # managed by Certbot




}